spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: "000000"
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      prefix: /
      suffix: .jsp
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qf.p11.pojo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl